version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: stock-management-postgres
    environment:
      POSTGRES_DB: stock-management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: